# Generated by Django 3.1.1 on 2020-10-03 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seat_id', models.CharField(max_length=3, null=True)),
                ('M_Show', models.CharField(blank=True, choices=[('occupied', 'occupied'), ('selected', 'selected'), ('', '')], max_length=50, null=True)),
                ('N_Show', models.CharField(blank=True, choices=[('occupied', 'occupied'), ('selected', 'selected'), ('', '')], max_length=50, null=True)),
                ('F_Show', models.CharField(blank=True, choices=[('occupied', 'occupied'), ('selected', 'selected'), ('', '')], max_length=50, null=True)),
                ('S_Show', models.CharField(blank=True, choices=[('occupied', 'occupied'), ('selected', 'selected'), ('', '')], max_length=50, null=True)),
                ('Customer_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Movie_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hub.movies')),
            ],
        ),
    ]
