# Generated by Django 3.1.1 on 2020-10-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='F_Show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='M_Show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='N_Show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='S_Show',
            field=models.BooleanField(default=False),
        ),
    ]
