# Generated by Django 3.1.1 on 2020-10-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0003_auto_20201004_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='F_Show',
            new_name='A1',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='M_Show',
            new_name='A2',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='N_Show',
            new_name='A3',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='S_Show',
            new_name='A4',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Seat_id',
        ),
    ]
