# Generated by Django 3.1.1 on 2020-10-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0007_auto_20201021_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=254)),
                ('Number', models.IntegerField()),
                ('Seats', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
