# Generated by Django 3.1.1 on 2020-11-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0011_auto_20201102_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_heading',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_review',
            field=models.TextField(max_length=500),
        ),
    ]
