# Generated by Django 3.1.1 on 2020-11-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0012_auto_20201102_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date_of_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='date_of_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
