# Generated by Django 3.1.1 on 2020-11-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0013_auto_20201103_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Customer_Name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='Movie_Name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
