# Generated by Django 3.1.1 on 2020-11-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0014_auto_20201103_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Date_Of_Show',
            field=models.DateField(blank=True, null=True),
        ),
    ]
